name: Restore Node.js env

description: Restore the task runner infrastructure by Node.js

runs:
  using: 'composite'
  steps:
    - name: Setup node.js
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
      with:
        node-version-file: ./.node-version

    - name: Setup pnpm
      uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10

    - name: cache node_modules
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
      with:
        path: |
          ./node_modules
          ./packages/*/node_modules
        key: node-${{ hashFiles('**/pnpm-lock.yaml') }}

    - name: install node_modules
      shell: bash
      run: pnpm install --frozen-lockfile
