name: test

on:
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Initialize
        uses: ./.github/actions/restore-node

      - name: Run Lint
        run: pnpm -r lint

      - name: Run Test
        run: pnpm -r test
